# Generated by Django 5.1 on 2025-10-02 01:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('target_audience', models.CharField(choices=[('Baby', 'Baby'), ('Mother', 'Mother')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('Boy', 'Boy'), ('Girl', 'Girl')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('appt_datetime', models.DateTimeField(verbose_name='Appointment Date & Time')),
                ('purpose', models.TextField()),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='tracker.baby')),
            ],
        ),
        migrations.CreateModel(
            name='FeedingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeding_time', models.DateTimeField()),
                ('feeding_type', models.CharField(choices=[('Breast Milk', 'Breast Milk'), ('Formula', 'Formula'), ('Solids', 'Solids')], max_length=20)),
                ('amount_ml', models.PositiveIntegerField(blank=True, null=True, verbose_name='Amount (ml)')),
                ('notes', models.TextField(blank=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_logs', to='tracker.baby')),
            ],
        ),
        migrations.CreateModel(
            name='GrowthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Height (cm)')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight (kg)')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_logs', to='tracker.baby')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_title', models.CharField(max_length=100)),
                ('milestone_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='tracker.baby')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_logs', to='tracker.baby')),
            ],
        ),
    ]
