# Generated by Django 5.1 on 2025-10-02 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recommended_age_weeks', models.IntegerField(help_text='Recommended age in weeks for the vaccination.')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_administered', models.DateField()),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.baby')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.vaccine')),
            ],
            options={
                'unique_together': {('baby', 'vaccine')},
            },
        ),
    ]
